# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTIzYmM5ZDA5NmNhNzMxZmMyNzZhODQ0ZDVlODE3NmUxNjU1YTc0MmFmZGNlZjk3YmRjMWMwZTk3MmRiYWI0MDg3Njk5ZWJiOTQ4NTgwNDllNjRkMGVmNDgxOWY2MDRjYTkzYTlmNzI1NjBjN2VmN2U2ZTllZmNkOTQxNWI5ZmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
